Repository stretchr/objx, pull requests merged in 2018-05, with the labels that each got.

#68 Drop go 1.6 & 1.7 support
  .travis.yml
  README.md
Labels: 4. to release, Changelog: Needed

#69 Fix indentation
  .travis.yml
  Taskfile.yml
  codegen/template.txt
  codegen/template_test.txt
  map_test.go
  type_specific_codegen.go
  type_specific_codegen_test.go
Labels: 4. to release

#65 Fixed incorrect result for obj.Value().MSI() getter
  type_specific_codegen.go
  type_specific_codegen_test.go
Labels: 4. to release, Changelog: Needed

#63 URLValues without sprinf, support for maps and slices
  conversions.go
  conversions_test.go
  value.go
  value_test.go
Labels: 4. to release, Changelog: Needed, enhancement

#76 Nil value returns empty string.
  value.go
  value_test.go
Labels: 4. to release

#77 Add PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 4. to release

#78 Fix lint
  .travis.yml
  Taskfile.yml
Labels: 4. to release

#79 Update travis file
  .travis.yml
Labels: 4. to release, technical debt
