Repository stretchr/objx, pull requests merged in 2019-04, with the labels that each got.

#90 Update to go 1.12
  .travis.yml
Labels: 4. to release

#93 Updated Map accessors
  accessors.go
  accessors_test.go
Labels: 4. to release, Changelog: Needed

#94 Check more errors in tests
  conversions_test.go
Labels: 4. to release, enhancement

#95 Fixes #88
  accessors.go
  accessors_test.go
Labels: 4. to release
